name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build Binary
      run: |
        export DEVKITPRO=/opt/devkitPro
        mkdir -p $DEVKITPRO/wut/share/
        touch $DEVKITPRO/wut/share/wut_rules
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
        echo "VERSION=$(make get_version)" >> $GITHUB_ENV
        echo Version is ${{ env.VERSION }}
    - uses: actions/upload-artifact@v3
      with:
        name: EnvSwap-${{ env.VERSION }}
        path: "./EnvSwap-${{ env.VERSION }}.zip"
